language: java
script: mvn package
before_install:
- openssl aes-256-cbc -K $encrypted_3fd0ad2add15_key -iv $encrypted_3fd0ad2add15_iv
  -in barta3.pem.enc -out barta3.pem -d
  
- chmod 600 barta3.pem

after_success:

#- echo -e "Host amazonaws.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#- ssh -i barta3.pem -o "StrictHostKeyChecking no" ubuntu@ec2-52-28-32-122.eu-central-1.compute.amazonaws.com

- scp -i barta3.pem -o "StrictHostKeyChecking no" ch.bfh.bti7515.waschfritz.rest/target/ch.bfh.bti7515.waschfritz.rest-1.1.9.RELEASE.jar ubuntu@ec2-52-28-32-122.eu-central-1.compute.amazonaws.com:/home/ubuntu/deployment